"""
Django settings for api_genai_reaseguros project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Robust .env loading: try BASE_DIR and parent directory (for Docker compatibility)
env_file_path = os.path.join(BASE_DIR, ".env")
if not os.path.exists(env_file_path):
    env_file_path = os.path.join(BASE_DIR.parent, ".env")

if os.path.exists(env_file_path):
    environ.Env.read_env(env_file_path)

PROJECT_ID = env('PROJECT_ID', default=None)
API_CORE_URL = env('API_CORE_URL', default=None)
LOGGING_TYPE = env('LOGGING_TYPE', default='LOCAL')

# Handle Google Credentials
GOOGLE_APPLICATION_CREDENTIALS = env('GOOGLE_APPLICATION_CREDENTIALS', default=None)
if GOOGLE_APPLICATION_CREDENTIALS:
    # Try finding the file in BASE_DIR or BASE_DIR.parent if path is relative
    if not os.path.isabs(GOOGLE_APPLICATION_CREDENTIALS):
        potential_path = os.path.join(BASE_DIR, GOOGLE_APPLICATION_CREDENTIALS)
        if not os.path.exists(potential_path):
            potential_path = os.path.join(BASE_DIR.parent, GOOGLE_APPLICATION_CREDENTIALS)
        GOOGLE_APPLICATION_CREDENTIALS = potential_path
    
    if os.path.exists(GOOGLE_APPLICATION_CREDENTIALS):
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GOOGLE_APPLICATION_CREDENTIALS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x$p349#=%&l0jgnj0_!5!dl4xoh5sbmcs06gq-x43$6c$xz_c%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        'rest_framework',
    'documents'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_genai_reaseguros.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_genai_reaseguros.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Check if using Cloud SQL IAM authentication
CLOUD_SQL_CONNECTION_NAME = env.str("CLOUD_SQL_CONNECTION_NAME", default=None)

if CLOUD_SQL_CONNECTION_NAME:
    # Cloud Run environment with Cloud SQL IAM authentication
    from google.cloud.sql.connector import Connector
    import pg8000
    
    # Initialize Connector object
    connector = Connector()
    
    def getconn():
        conn = connector.connect(
            CLOUD_SQL_CONNECTION_NAME,
            "pg8000",
            user=env.str("DB_USER"),
            db=env.str("DB_NAME"),
            enable_iam_auth=True,
        )
        return conn
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.str("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": "",  # No password needed with IAM
            "HOST": "",  # Not used with connector
            "PORT": "",  # Not used with connector
            "OPTIONS": {
                "connect_factory": getconn,
            },
        }
    }
else:
    # Local development or traditional connection
    DATABASES = {
        "default": {
            "ENGINE": env.str("DB_ENGINE"),
            "NAME": env.str("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": env.str("DB_PASSWORD"),
            "HOST": env.str("DB_HOST"),
            "PORT": env.str("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
