# Generated by Django 4.2.18 on 2025-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_core_id', models.IntegerField(verbose_name='api_core_id')),
                ('document_type', models.TextField(default=list, verbose_name='document_type')),
                ('prompt', models.TextField(default='Analiza los contratos y poliza', verbose_name='prompt')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AgentGarden',
            },
        ),
    ]
