# Generated by Django 4.2.18 on 2025-11-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
    ]
